version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/demo-project
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: ./installApp.sh
      timeout: 300
      runas: ubuntu
  