#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.
  
image: openjdk:11

clone:
  depth: full   
  
definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &continuous-integration
        name: Build
        caches:
          - gradle
          - sonar
        script:
          - chmod +x gradlew
          - ./gradlew build sonarqube
        artifacts:
          - build/libs/**
          
    - step: &uploadS3
        caches:
          - gradle
        name: Upload repository to Bucket
        script:
          - chmod +x gradlew
          - ./gradlew build
          - apt-get update
          - apt-get install -y zip
          - zip -j tech.zip build/libs/spep-0.0.1-SNAPSHOT.jar appspec.yml installApp.sh
          - pipe: atlassian/aws-code-deploy:0.2.10
            variables:
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              COMMAND: 'upload'
              APPLICATION_NAME: $APPLICATION_NAME
              ZIP_FILE: 'tech.zip'
              VERSION_LABEL: 'my-app-1.0.0'
              S3_BUCKET: $S3_BUCKET       
              
    - step: &continous-deployment-AWS
        name: Deploy to AWS
        deployment: production
        script:
          - pipe: atlassian/aws-code-deploy:0.2.10
            variables:
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              APPLICATION_NAME: $APPLICATION_NAME
              DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
              S3_BUCKET: $S3_BUCKET
              COMMAND: 'deploy'
              WAIT: 'true'
              VERSION_LABEL: 'my-app-1.0.0'
              IGNORE_APPLICATION_STOP_FAILURES: 'true'
              FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
pipelines:
  branches:
    master:     
      - step: *continuous-integration
      - step: *uploadS3
      - step: *continous-deployment-AWS